name: Backend CD

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/steplidia/solar-cell-api

jobs:
  publish:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: solar-profitability-estimator

    steps:
      - uses: actions/checkout@v7

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -f ./src/SolarProfitabilityEstimator.Api/Dockerfile \
            -t $IMAGE_NAME:${{ github.sha }} \
            -t $IMAGE_NAME:latest \
            .

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest